;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[colors]
background = #11111b
foreground = #cdd6f4
blue = #89b4fa
pink = #f5c2e7
gray = #313244

[bar/main]
width = 100%
height = 30
radius = 0
background = ${colors.background}
foreground = ${colors.foreground}
tray-position = right

padding-left = 0.5
padding-right = 0.5

module-margin = 0

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=16;3
font-1 = JetBrainsMono Nerd Font:size=18;5
font-2 = Material Design Icons:style=Bold:size=22;3
font-3 = unifont:fontformat=truetype:size=18:antialias=true;

modules-left = filesystem
modules-center = space bspwm space
modules-right = battery sound xkeyboard time space wlan

[module/bspwm]
type = internal/bspwm

pin-workspaces = true
inline-mode = true
enable-click = true
enable-scroll = true
reverse-scroll = false

format = <label-state>
label-separator = ""
label-focused-foreground = ${colors.pink}

[module/space]
type = custom/text
content = " "

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
label-layout-padding = 1
label-layout-foreground = #fff
label-indicator-on = %name%
layout-icon-default = some-icon
layout-icon-0 = us
layout-icon-1 = ua
layout-icon-2 = ru
label-indicator-on-capslock = !
label-indicator-off-capslock =

[module/time]
type = internal/date
interval = 60
format = <label>
#format-background = #2b2f37
date = %{F#cdd6f4} %H:%M %p%{F-}
time-alt = %{F#61afef}  %a, %d %b %Y%{F-}
label = %date%%time%

[module/wlan]
type = internal/network
interface-type = wireless
interval = 3
format-connected =  <label-connected>
label-connected = " "
label-connected-foreground = ${colors.foreground}
format-disconnected = <label-disconnected>
label-disconnected = "󰖪 "
label-disconnected-foreground = ${colors.foreground}

[module/filesystem]
type = custom/text 
content =" " 
content-padding =1
click-left = rofi -show drun
content-foreground =  #61afef

[module/battery]
type = internal/battery
#full-at = 98
#low-at = 10

battery = BAT0
adapter = ACAD
poll-interval = 5

time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <label-low> <animation-low>

label-charging = "%percentage%% "
label-discharging = "%percentage%% "
label-full = " 100% "
label-low = "%percentage% "

ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
bar-capacity-width = 10

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-framerate = 910

animation-discharging-0 = " "
animation-discharging-1 = " "
animation-discharging-2 = " "
animation-discharging-3 = " "
animation-discharging-4 = " "
animation-discharging-framerate = 500

animation-low-0 = "  "
animation-low-1 = "  "
animation-low-framerate = 1500

animation-low-foreground = ${colors.foreground}
label-charging-foreground = ${colors.foreground}
format-discharging-foreground = ${colors.foreground}
label-discharging-foreground = ${colors.foreground}
format-full-prefix-foreground = ${colors.foreground}
ramp-capacity-foreground =  ${colors.foreground}
animation-charging-foreground = ${colors.foreground}

[module/sound]
type = internal/alsa
format-volume = <ramp-volume> <label-volume>
format-volume-padding = 1
format-muted = 󰖁
format-muted-padding = 1
label-volume = %percentage%%
ramp-volume-0 = 󰖀 %{F-}
ramp-volume-1 = 󰖀 %{F-}
ramp-volume-2 = 󰖀 %{F-}
ramp-volume-3 = 󰖀 %{F-}
ramp-volume-4 = 󰖀 %{F-}
ramp-volume-5 = 󰕾 %{F-}
ramp-volume-6 = 󰕾 %{F-}
ramp-volume-7 = 󰕾 %{F-}
ramp-volume-8 = 󰕾 %{F-}
ramp-volume-9 = 󰕾 %{F-}
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = ${colors.foreground}
format-muted-foreground = #cdd6f4
